// // Question-1

// let num = prompt ('Enter a number:');

// if (num % 5 === 0) {
//     console.log(num,"is multiple of 5");
// } else {
//     console.log(num,"is not multiple of 5");
// }

// // Question-02

// let score = 55 ;

// if (score >=90 && score <=100) {
//     Grade = "A";
// } else if (score >=70 && score <= 89) {
//     Grade = "B";
// } else if (score >=50 && score <= 69) {
//     Grade = "C";
// } else if (score >=0 && score <= 49) {
//     Grade = "F";
// }

// console.log("According to your Score, Your Grade =", Grade);